### ISSUE TITLE
ULMFit for tokenisation

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#222]
**Describe the bug**
I'm trying to evaluate the tokenisation performance of ULMFit. However, it seems the algorithm isn't used when specifying `engine=ulmfit`. The code is using the `newmm` engine instead (https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/__init__.py#L70).

Is this a mistake? or it should be this way. If not, may I ask you how I can use ULMFit for tokenisation via PyThaiNLP.

**Desktop (please complete the following information):**
 - OS: OSX
 - Python Version 3.7.2
 - Version 2.0.5

**Comment by artificiala** [comment]
Hi @heytitle,

When specifying engine as ulmfit, the tokenizer then uses the newmm engine with the dictionary designed for ulmfit (pythainlp/corpus/words_th_frozen_201810.txt)

ULMFit is a technique to train a language model and fine-tune the model for downstream tasks (i.e. text classification). For instance, predicting the sentiment of a user's comment either positive or negative, it first tokenizes the user's comment, converts each word into its representation (embedding vector). Then, it feeds to LSTM encoders and combines with another classification model. Basically, this tokenizes the text, encode and predict its sentiment.

As ULMFit model for Thai language was trained with the following dictionary, it needs to use exactly the same dictionary in order to convert each tokenized word into its word vector. 

For more information, you could check out [this post](https://medium.com/mlreview/understanding-building-blocks-of-ulmfit-818d3775325b).

The main contributor to ULMFit model is Khun Charin @cstorm125.

Cheers,

**Comment by heytitle** [comment]
@artificiala if I understand correctly, setting `engine=ulmfit` means using the corresponding dictionary for ULMFit models? I thought we had a ULMFit model for tokenisation. 

Please correct me if I'm wrong.

**Comment by artificiala** [comment]
@heytitle You are right, with```engine=ulmfit``` means using the dictionary for ULMFit model. 

One of the example use cases is to vectorize a Thai sentence.

```
from pythainlp.word_vector import sentence_vectorizer

sentence_vectorizer('ลูนา 1 เป็นยานอวกาศลำแรกในโครงการลูนาของโซเวียต')
```

```sentence_vectorizer``` returns one vector with 300 dimensions representing the sentence.

**Comment by heytitle** [comment]
ok, got it now. I would suggest to use a different name for this purpose to prevent this confusion. 

For example, one might use `engine=newmm-ulmfit-frozen-dict` instead.

**Comment by bact** [comment]
Or maybe, this "ulmfit" shouldn't be around anymore publicly. Since this option will only be used internally for thai2fit-related code.

I proposed that we should remove "ulmfit" option for `engine` in `word_tokenize()`.

For code that require this functionality, it can be implemented easily by using the new `Tokenizer` class and specify `FROZEN_DICT_TRIE` as its `custom_dict`.

**Comment by cstorm125** [comment]
I think we should retain the option publicly because we also provide some utility for training the fastai model in `pythainlp.ulmfit`. I don't think it would be confusing since ULMFit is explicitly at word-level, language modeling algorithm used mainly for text classification.

**Comment by cstorm125** [comment]
Accepted PR by @bact. Closing this now.
