### ISSUE TITLE
Problem with syllable tokenization

### ISSUE THREAD

**Issue by p16i** [PyThaiNLP/pythainlp#461]
**Describe the bug**
I've observed a behavior that is worth being discussed here. In short, when there are some punctuations, syllable tokenizes would return some incorrect syllables, both from the default engine and `ssg`.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1214890/89706026-820af500-d962-11ea-8e21-15461a2f7b7c.png">

**To Reproduce**
Please see: https://colab.research.google.com/drive/12gxSmskjHCQzqV1-Nb4IOaBD-LJ0ARl5?usp=sharing

**Expected behavior**
imho, the expected result is `['หน้า', 'ที่', ' ', '19', '...'] `. To achieve this, we can split the sentence by punctuation first then do syllable tokenization for each part.

What do you think?

**Comment by wannaphong** [comment]
I think we should report this problem to [ssg](https://github.com/ponrawee/ssg).

**Comment by p16i** [comment]
that's true but we also see here that the default engine doesn't split `19...` either.

**Comment by bact** [comment]
Since syllable doesn't involve anything with punctuation (unlike word that can have punctuation like "โควิด-19" "ก.พ.), i think it's safe to split at punctuations first then do the syllable tokenization

**Comment by wannaphong** [comment]
OK. We will remove syllable_tokenize in 2.4 (move to subword_tokenize)

**Comment by bact** [comment]
> that's true but we also see here that the default engine doesn't split `19...` either.

Current `newmm` engine will group that together, due to this:
https://github.com/PyThaiNLP/pythainlp/blob/7497f1b8dbe1d9dd6edb7efda78093d4a1c0e2ea/pythainlp/tokenize/newmm.py#L104-L106

`_PAT_NONTHAI` is
https://github.com/PyThaiNLP/pythainlp/blob/7497f1b8dbe1d9dd6edb7efda78093d4a1c0e2ea/pythainlp/tokenize/newmm.py#L25-L33

I agree with @heytitle that we probably need to think about `19...` case.

Our current tokenization is focus on Thai word tokenization and probably not cover all the things we should do with punctuation, etc, in general.

**Comment by bact** [comment]
Fixed for newmm.

For ssg, I filed a new issue at https://github.com/ponrawee/ssg/issues/8
